name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]


jobs:
  build_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Npm install
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
  deployment_pipeline:
    if: ${{github.event_name == 'push'}}
    runs-on: ubuntu-latest
    needs: [build_pipeline]
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "react-node-js-app-demo"
          heroku_email: "dmurilloferrer@gmail.com"
          healthcheck: "https://react-node-js-app-demo.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
  tag_release:
    if: ${{github.event_name == 'push' &&	contains(join(github.event.commits.*.message), '#skip')}}
    runs-on: ubuntu-latest
    needs: [build_pipeline, deployment_pipeline]
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  a_test_job:
    runs-on: ubuntu-latest
    needs: [build_pipeline, deployment_pipeline, tag_release]
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          NEW_COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "$NEW_COMMIT_MESSAGES"
